### ISSUE TITLE
アンカーリンクのバグ

### ISSUE THREAD

**Issue by ANTON072** [Takazudo/jQuery.LazyJaxDavis#8]
使わせていただこうと思ったら、ひとつバグ？を発見しました。

このデモのページで、
http://takazudo.github.io/jQuery.LazyJaxDavis/demos/anchorhandler/

例えばサイドバーの page1.html#moo をクリックすると、
http://takazudo.github.io/jQuery.LazyJaxDavis/demos/anchorhandler/pages/page1.html#moo

に飛びます。
そのページ内のページ内リンク #bar をクリックすると、
http://gyazo.com/2524b716c71a0ff670bcaf750093108e

一旦 #bar にスクロールしてから、ページトップに進んでしまいます。
が、ページトップに進んでからページ内リンクをクリックすると正常な動作をします。

最初のクリックのときだけ、router.bind "everyfetchstart" が二度実行されてしまっている？

原因おわかりになりますでしょうか？？

**Comment by ANTON072** [comment]
とりあえず自分がやりたいことは直せたのでプルリクエストしてみました！
他に影響あったりしたらすいません・・・
https://github.com/ANTON072/jQuery.LazyJaxDavis/tree/fix/mydevelop

**Comment by Takazudo** [comment]
おおっ、ありがとうございます！あとで確認してみます！
取り急ぎ。

**Comment by Takazudo** [comment]
ちょっと突っ込んで検証しきれなかったのですが、
原因としては、同じページ内にあるアンカーへのリンクであっても、
別ページとして判断されることがあったみたいで、そのようになっていました。
頂いた修正とはちょっと別の所を修正したのですが、これで直ってると思います。
別ページへの遷移なのかどうかをチェックする箇所で、アンカーを除外してチェックさせるようにしました。
ありがとうございます！

**Comment by ANTON072** [comment]
ありがとうございました！

**Comment by Takazudo** [comment]
こちらこそどーもです！
